import streamlit as st
import pandas as pd
import time
import os

# Try importing the LLM summary from Person 1 (it may not exist yet)
try:
    import llm_summary
except ImportError:
    llm_summary = None

# Configure the Streamlit page
st.set_page_config(page_title="News Pulse Dashboard", layout="wide")

# Title
st.title("📰 News Pulse Live Dashboard")

# Function to safely load CSV data
def load_data(filepath):
    if os.path.exists(filepath):
        try:
            return pd.read_csv(filepath)
        except Exception:
            return pd.DataFrame()
    return pd.DataFrame()

# Load the data generated by the Spark streaming job
source_df = load_data("data/output/by_source.csv")
window_df = load_data("data/output/by_window.csv")
top_words_df = load_data("data/output/top_words.csv")

# Create layout with columns
col1, col2 = st.columns(2)

with col1:
    st.subheader("Source Mix")
    if not source_df.empty:
        st.bar_chart(source_df.set_index('source'))
    else:
        st.info("Waiting for source data...")

with col2:
    st.subheader("Hourly Volume")
    if not window_df.empty:
        # Create a combined 'window' label or just use 'window_start'
        if 'window_start' in window_df.columns:
            chart_data = window_df.set_index('window_start')
            st.line_chart(chart_data['count'])
        else:
            st.line_chart(window_df)
    else:
        st.info("Waiting for window data...")

st.markdown("---")

col3, col4 = st.columns([1, 2])

with col3:
    st.subheader("Top 10 Keywords")
    if not top_words_df.empty:
        st.dataframe(top_words_df, use_container_width=True)
    else:
        st.info("Waiting for top words data...")

with col4:
    st.subheader("LLM Summary")
    
    # Try generating a summary based on top words
    if not top_words_df.empty:
        top_words_list = top_words_df['word'].tolist()
        
        if llm_summary and hasattr(llm_summary, 'generate_summary'):
            try:
                summary_text = llm_summary.generate_summary(top_words_list)
                st.write(summary_text)
            except Exception as e:
                st.warning(f"Error calling LLM summary: {e}")
                st.write(f"**Fallback Summary:** The current top news trends revolve around these keywords: {', '.join(top_words_list[:5])}.")
        else:
            st.write(f"**Fallback Summary (llm_summary.py not found/ready):** The current top news trends revolve around these keywords: {', '.join(top_words_list[:5])}.")
    else:
        st.info("Waiting for keywords to generate summary...")

# Auto-refresh every 5 seconds
time.sleep(5)
st.rerun()
